### ISSUE TITLE
Unknown features and feature conflicts

### ISSUE THREAD

**Issue by kbatsuren** [unimorph/sjo#2]
Hi @gisly,

I have found some issues with the data. Could you please correct them?

The unknown feature is `DIST`.

```
ᡨᡝᠰᡠ	ᡨᡝᠰᡠ	PRO;DIST
ᡨᡝᠷᡝ	ᡨᡝᠷᡝ	DET;DIST
```

The feature conflict is between `SBJV` and `IND` or `COND` and `IND`:

`ᠣᠮᠪᡞ	ᠣᡪᠣᠷᠠᡥᡡ	V;ACT;FIN;IND;PRS;SBJV`

**Comment by gisly** [comment]
Hi! 
1) DIST was thought to be the label for the marker for the remote pronoun. Should I replace it with REM or simply remove it?

2) Thank you, I'll look into it and check it once more

**Comment by kbatsuren** [comment]
In that case, I think you can replace `DIST` with `LGSPEC01`. Thanks. 

No worries. Take your time.

**Comment by gisly** [comment]
@kbatsuren , please look at https://github.com/unimorph/sjo/pull/3 
I changed `DIST` to `LGSPEC01` and removed `IND`, which was wrong

**Comment by kbatsuren** [comment]
Thanks for the fast work! This pull request should fix the problem. 

I close this issue. Thank you very much again!

**Comment by gisly** [comment]
Hi @kbatsuren ! Sorry for the delay, I will now merge the PR
